exclude: |
  (?x)^(
      external|
      bazel-.*/|
      third_party/.*|
      zview/graphics_backend/imgui_impl*
  )

repos:
  - repo: https://github.com/warchant/pre-commit-buildifier
    rev: 0.1.1
    hooks:
      - id: buildifier
        args: ["--version=v7.1.1", "--lint=warn", "--warnings=all", "-v"]
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [-i, --style=Google]
      - id: clang-tidy
