repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [-i, --style=Google]
        exclude: src/graphics_backend/|src/vulkan_test/
      - id: clang-tidy
        args: [--fix-errors, -warnings-as-errors=*, -extra-arg=-std=c++20]
        exclude: src/graphics_backend/
      - id: cppcheck
        args: [--enable=all]
        exclude: src/graphics_backend/
      - id: cpplint
        args: [--verbose=0, --filter=-legal/copyright]
        exclude: src/graphics_backend/
