

cc_library(
    name = "mvp_mat",
    srcs = [
        "mvp_mat.cpp"
    ],
    hdrs = [
        "mvp_mat.h",
    ],
    deps = ["//src/types","//src/params",        "@imgui"],
    visibility = ["//visibility:public"],
    

)


