
cc_library(
    name = "input_device_handler",
    srcs = [
        "input_device_handler.cpp"
    ],
    hdrs = [
        "input_device_handler.h",
    ],
    deps = ["@imgui","//src/ui:vp_mat","//src/params"],
    visibility = ["//visibility:public"],
    

)




cc_library(
    name = "vp_mat",
    srcs = [
        "vp_mat.cpp"
    ],
    hdrs = [
        "vp_mat.h",
    ],
    deps = ["//src/types","//src/params"],
    visibility = ["//visibility:__pkg__"],
    

)


