
cc_library(
    name = "input_device_handler",
    srcs = [
        "input_device_handler.cpp"
    ],
    hdrs = [
        "input_device_handler.h",
    ],
    deps = ["@imgui"],
    visibility = ["//visibility:public"],
    

)


