
cc_library(
    name = "vp_mat",
    srcs = [
        "vp_mat.cpp"
    ],
    hdrs = [
        "vp_mat.h",
    ],
    deps = ["@eigen","//zview/common:common_types","//zview/common:params"],
    visibility = ["//visibility:public"],
    

)
