load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "params",
    srcs = [
        "params.cpp",
    ],
    hdrs = ["params.h"],
    visibility = ["//visibility:public"],
    deps = [
    ],
)
