load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "types",
    srcs = [
        "types.cpp"
    ],
    hdrs = [
        "types.h",
    ],

    
    deps = [
        "@eigen",
         "//src/opengl_backend",


    ],
        visibility = ["//visibility:public"],

)
