load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "shader_code",
    hdrs = [
        "edges_shader_code.h",
        "grid_shader_code.h",
        "mesh_shader_code.h",
        "pcl_shader_code.h",
        "picking_shader_code.h",
    ],
    visibility = ["//zview/graphics_backend:__pkg__"],
)
