load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "common_types",
    srcs = [
        "common_types.cpp",
    ],
    hdrs = [
        "common_types.h",
    ],
    
    deps = [
        "@eigen",
    ],
)
