load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
    name = "spv_to_header",
    srcs = ["spv_to_header.py"],
    main = "spv_to_header.py",
    visibility = ["//visibility:public"],
)
